# Generated by Django 3.2.19 on 2023-06-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0010_tvshowproxy_tvshowseasonproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(default=[('MOV', 'Movie'), ('TVS', 'TV Show'), ('SEA', 'Season'), ('PLA', 'Playlist')], max_length=3),
        ),
    ]
