# Generated by Django 3.2.19 on 2023-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0012_alter_playlist_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('MOV', 'Movie'), ('TVS', 'TV Show'), ('SEA', 'Season'), ('PLA', 'Playlist')], default=[('MOV', 'Movie'), ('TVS', 'TV Show'), ('SEA', 'Season'), ('PLA', 'Playlist')], max_length=3),
        ),
    ]
