# Generated by Django 3.2.19 on 2023-06-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0013_alter_playlist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
