# Generated by Django 3.2.19 on 2023-06-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0014_movieproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieproxy',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
